config/routes.rb
Rails.application.routes.draw do

  scope module: :web do
    root 'welcome#new'
    get 'logout', to: 'sessions#destroy', as: 'logout'
    namespace :user do
      root to: redirect(path: 'user/calendar')
      resources :events, except: [:show, :index]
      resource :calendar, only: :show
      
      resource :setting, only: [:edit, :update] do
        collection do
          get 'edit_password'
          patch 'update_password'
        end
      end
    end
    resource :session, only: [:new, :create, :destroy]
    resource :registration, only: [:new, :create]
    resource :calendar, only: :show
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user

  validates :title, presence: true, length: { maximum: 200 }
  validates :date, presence: true
  validates :reiteration, inclusion: {in: ['empty', 'daily', 'weekly', 'monthly', 'annually']}, allow_nil: true

  paginates_per 40

  scope :hidden, -> { where(private: true) }
  scope :visible, -> { where(private: false) }

  enum reiteration: [:empty, :daily, :weekly, :monthly, :annually]

  def self.calendar(date)
    where_clause = "(date >= :beginning_of_month and date <= :end_of_month) or 
                    (reiteration = 1 and date <= :date) or 
                    (reiteration = 2 and date <= :date) or
                    (
                      (reiteration = 4 or reiteration = 3) and 
                      extract(day from date) >= :beginning_of_month_day and 
                      extract(day from date) <= :end_of_month_day and
                      date <= :date
                    )"
    where(where_clause, 
      {
        date: date,
        beginning_of_month: date.at_beginning_of_month, 
        end_of_month: date.at_end_of_month,
        beginning_of_month_day: date.at_beginning_of_month.day,
        end_of_month_day: date.at_end_of_month.day
      })
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :events
  has_secure_password
  paginates_per 40

  validates :email, presence: true, length: {in: 6..255}, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }, uniqueness: true
  validates :name, presence: true, length: { in: 3..255 }
  validates :surname, presence: true, length: { in: 3..255 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  rescue_from ActionController::RoutingError, with: :handle_error
  rescue_from ActionController::InvalidAuthenticityToken, with: :handle_error
  rescue_from ActiveRecord::RecordNotFound, with: :handle_error

  protected
  def handle_error(exception = nil)
    logger.info "Rendering 404: #{exception ? exception.message : ''}: " + params.inspect
    render :file => "#{Rails.root}/public/404.html", status: :not_found, layout: false
  end
end

app/controllers/concerns/authenticable.rb
module Authenticable
  extend ActiveSupport::Concern

  included do
    include AuthHelper

    before_action :authenticate!

    helper_method :current_user, :signed_in?
  end

  def authenticate!
    raise 'must overload'
  end
end

app/controllers/concerns/authenticable_api.rb
module AuthenticableApi
  extend ActiveSupport::Concern
  include Authenticable

  def authenticate!
    render head: :forbidden unless signed_in?
  end
end

app/controllers/concerns/authenticable_web.rb
module AuthenticableWeb
  extend ActiveSupport::Concern
  include Authenticable

  def authenticate!
    redirect_to new_session_path unless signed_in?
  end
end

app/controllers/web/application_controller.rb
class Web::ApplicationController < ApplicationController
  include AuthenticableWeb
end

app/controllers/web/calendars_controller.rb
class Web::CalendarsController < Web::ApplicationController
  def show
    @events = CalendarService.make_calendar(params[:month], params[:year])
    @offset = CalendarService.get_offset(params[:month], params[:year])
  end
end

app/controllers/web/registrations_controller.rb
class Web::RegistrationsController < Web::ApplicationController
  skip_before_filter :authenticate!
  def new
    @user = ::User.new
  end

  def create
    @user = ::User.create(create_params)
    if @user.save
      sign_in @user
      redirect_to user_calendar_path
    else
      render :new
    end
  end
  
  private 
  def create_params
    params.require(:user).permit(:name, :surname, :email, :password)
  end
end

app/controllers/web/sessions_controller.rb
class Web::SessionsController < Web::ApplicationController
  skip_before_filter :authenticate!

  def new
    redirect_to user_calendar_path if signed_in?
    @session = UserForm.new
  end

  def create
    @session = UserForm.new session_params
    if @session.valid?
      sign_in @session.user
      redirect_to user_calendar_path
    else
      render :new
    end 
  end

  def destroy
    sign_out
    redirect_to root_url
  end

  private
  def session_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/web/welcome_controller.rb
class Web::WelcomeController < Web::ApplicationController
  skip_before_filter :authenticate!
  def new
    redirect_to user_calendar_path if signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/web/calendars_helper.rb
module Web::CalendarsHelper
end

app/helpers/web/registration_helper.rb
module Web::RegistrationHelper
end

app/helpers/web/sessions_helper.rb
module Web::SessionsHelper
end

app/helpers/web/user/calendars_helper.rb
module Web::User::CalendarsHelper
end

app/helpers/web/user/events_helper.rb
module Web::User::EventsHelper
end

app/helpers/web/user/settings_helper.rb
module Web::User::SettingsHelper
end

app/helpers/web/users_helper.rb
module Web::UsersHelper
end

app/helpers/web/welcome_helper.rb
module Web::WelcomeHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Календарь
    %link{:href => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css", :rel => "stylesheet"}
    %link{:href => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css", :rel => "stylesheet"}
    %link{:href => "https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css", :rel => "stylesheet"}
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    - if current_user
      .user-info{'data-name': current_user.name, 'data-surname': current_user.surname}
    = render 'shared/header'
    .container
      - if flash[:error]
        .alert.alert-danger
          %a.close{"data-dismiss" => "alert"} ×
          = flash[:error]
      - if flash[:notice]
        .alert.alert-info
          %a.close{"data-dismiss" => "alert"} ×
          = flash[:notice]
      = yield
    %script{:src => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"}

app/views/shared/_header.html.haml
%nav.navbar.navbar-default
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{href: root_path} Календарь
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li
          %a{href: "#{}"}
      %ul.nav.navbar-nav.navbar-right
        - if current_user
          %ul.navbar-text
            = current_user.fullname
          %ul.nav.navbar-nav
            %li.dropdown
              %a.dropdown-toggle.glyphicon.glyphicon-cog{"data-toggle" => "dropdown", :href => "#"}
              %ul.dropdown-menu
                %li
                  %a{href: edit_user_setting_path}
                    Настройки
                    %span.glyphicon.glyphicon-cog.pull-right
                %li.divider
                %li
                  %a{href: calendar_path}
                    Все события
                    %span.glyphicon.glyphicon-fire.pull-right
                %li
                  %a{href: user_calendar_path}
                    Мой календарь
                    %span.glyphicon.glyphicon-time.pull-right
                %li.divider
                %li
                  %a{href: new_user_event_path}
                    Создать событие
                    %span.glyphicon.glyphicon-plus.pull-right
                %li.divider
                %li
                  %a{href: logout_path}
                    Выйти
                    %span.glyphicon.glyphicon-log-out.pull-right
        - else
          %li= link_to "Зарегистрироваться", new_registration_path
          %li
            .navbar-text или
          %li= link_to "Войти", new_session_path