config/routes.rb
Rails.application.routes.draw do

  scope module: :web do
    root 'welcome#new'
    get 'logout', to: 'sessions#destroy', as: 'logout'
    namespace :user do
      root to: redirect(path: 'user/calendar')
      resources :events, except: [:show, :index]
      resource :calendar, only: :show
      
      resource :setting, only: [:edit, :update] do
        collection do
          get 'edit_password'
          patch 'update_password'
        end
      end
    end
    resource :session, only: [:new, :create, :destroy]
    resource :registration, only: [:new, :create]
    resource :calendar, only: :show
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user

  validates :title, presence: true, length: { maximum: 200 }
  validates :date, presence: true
  validates :reiteration, inclusion: {in: ['empty', 'daily', 'weekly', 'monthly', 'annually']}, allow_nil: true

  paginates_per 40

  scope :hidden, -> { where(private: true) }
  scope :visible, -> { where(private: false) }

  enum reiteration: [:empty, :daily, :weekly, :monthly, :annually]

  def self.calendar(date)
    where_clause = "(date >= :beginning_of_month and date <= :end_of_month) or 
                    (reiteration = 1 and date <= :date) or 
                    (reiteration = 2 and date <= :date) or
                    (
                      (reiteration = 4 or reiteration = 3) and 
                      extract(day from date) >= :beginning_of_month_day and 
                      extract(day from date) <= :end_of_month_day and
                      date <= :date
                    )"
    where(where_clause, 
      {
        date: date,
        beginning_of_month: date.at_beginning_of_month, 
        end_of_month: date.at_end_of_month,
        beginning_of_month_day: date.at_beginning_of_month.day,
        end_of_month_day: date.at_end_of_month.day
      })
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :events
  has_secure_password
  paginates_per 40

  validates :email, presence: true, length: {in: 6..255}, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }, uniqueness: true
  validates :name, presence: true, length: { in: 3..255 }
  validates :surname, presence: true, length: { in: 3..255 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  rescue_from ActionController::RoutingError, with: :handle_error
  rescue_from ActionController::InvalidAuthenticityToken, with: :handle_error
  rescue_from ActiveRecord::RecordNotFound, with: :handle_error

  protected
  def handle_error(exception = nil)
    logger.info "Rendering 404: #{exception ? exception.message : ''}: " + params.inspect
    render :file => "#{Rails.root}/public/404.html", status: :not_found, layout: false
  end
end

app/controllers/concerns/authenticable.rb
module Authenticable
  extend ActiveSupport::Concern

  included do
    include AuthHelper

    before_action :authenticate!

    helper_method :current_user, :signed_in?
  end

  def authenticate!
    raise 'must overload'
  end
end

app/controllers/concerns/authenticable_api.rb
module AuthenticableApi
  extend ActiveSupport::Concern
  include Authenticable

  def authenticate!
    render head: :forbidden unless signed_in?
  end
end

app/controllers/concerns/authenticable_web.rb
module AuthenticableWeb
  extend ActiveSupport::Concern
  include Authenticable

  def authenticate!
    redirect_to new_session_path unless signed_in?
  end
end

app/controllers/web/application_controller.rb
class Web::ApplicationController < ApplicationController
  include AuthenticableWeb
end

app/controllers/web/calendars_controller.rb
class Web::CalendarsController < Web::ApplicationController
  def show
    @events = CalendarService.make_calendar(params[:month], params[:year])
    @offset = CalendarService.get_offset(params[:month], params[:year])
  end
end

app/controllers/web/registrations_controller.rb
class Web::RegistrationsController < Web::ApplicationController
  skip_before_filter :authenticate!
  def new
    @user = ::User.new
  end

  def create
    @user = ::User.create(create_params)
    if @user.save
      sign_in @user
      redirect_to user_calendar_path
    else
      render :new
    end
  end
  
  private 
  def create_params
    params.require(:user).permit(:name, :surname, :email, :password)
  end
end

app/controllers/web/sessions_controller.rb
class Web::SessionsController < Web::ApplicationController
  skip_before_filter :authenticate!

  def new
    redirect_to user_calendar_path if signed_in?
    @session = UserForm.new
  end

  def create
    @session = UserForm.new session_params
    if @session.valid?
      sign_in @session.user
      redirect_to user_calendar_path
    else
      render :new
    end 
  end

  def destroy
    sign_out
    redirect_to root_url
  end

  private
  def session_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/web/user/application_controller.rb
class Web::User::ApplicationController < Web::ApplicationController
end

app/controllers/web/user/calendars_controller.rb
class Web::User::CalendarsController < Web::User::ApplicationController
  def show
    @events = CalendarService.make_calendar(params[:month], params[:year], current_user)
    @offset = CalendarService.get_offset(params[:month], params[:year])
  end
end

app/controllers/web/user/events_controller.rb
class Web::User::EventsController < Web::User::ApplicationController 
  before_filter :set_event, only: [:update, :destroy]

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.new event_params
    if @event.save
      redirect_to user_calendar_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @event.update event_params
      redirect_to user_calendar_path
    else
      render :new
    end
  end

  def destroy
    @event.destroy
    redirect_to user_calendar_path
  end

  private 
  def event_params
    params.require(:event).permit(:title, :date, :reiteration, :private)
  end

  def set_events
    @events = current_user.events.page(params[:page]).decorate
  end

  def set_event
    @event = current_user.events.find(params[:id])
  end
end

app/controllers/web/user/settings_controller.rb
class Web::User::SettingsController < Web::User::ApplicationController
  def edit
    # Костыль, почему-то .dup не копирует этот объетк
    @user = ::User.find current_user.id
  end

  def update
    # Костыль, почему-то .dup не копирует этот объетк
    @user = ::User.find current_user.id
    if @user.update(update_params)
      redirect_to user_calendar_path
    else
      render :edit
    end
  end

  def edit_password
    @user = UserUpdatePasswordForm.new
  end

  def update_password
    pars = update_password_params
    pars[:email] = current_user.email
    @user = UserUpdatePasswordForm.new pars
    if @user.save
      redirect_to user_calendar_path
    else
      render :edit_password
    end
  end

  private
  def update_params
    params.require(:user).permit(:name, :surname, :email)
  end

  def update_password_params
    params.require(:user_update_password).permit(:old_password, :new_password)
  end
end

app/controllers/web/welcome_controller.rb
class Web::WelcomeController < Web::ApplicationController
  skip_before_filter :authenticate!
  def new
    redirect_to user_calendar_path if signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/web/calendars_helper.rb
module Web::CalendarsHelper
end

app/helpers/web/registration_helper.rb
module Web::RegistrationHelper
end

app/helpers/web/sessions_helper.rb
module Web::SessionsHelper
end

app/helpers/web/user/application_helper.rb
module Web::User::ApplicationHelper
end

app/helpers/web/user/calendars_helper.rb
module Web::User::CalendarsHelper
end

app/helpers/web/user/dashboard_helper.rb
module Web::User::DashboardHelper
end

app/helpers/web/user/events_helper.rb
module Web::User::EventsHelper
end

app/helpers/web/user/settings_helper.rb
module Web::User::SettingsHelper
end

app/helpers/web/users_helper.rb
module Web::UsersHelper
end

app/helpers/web/welcome_helper.rb
module Web::WelcomeHelper
end

app/views/web/user/calendars/show.html.haml
%h1.calendar-title= "#{I18n.t("date.month_names")[@events[0].date.month]} #{@events[0].date.year}"
.calendar-pagination
  = link_to '<<', user_calendar_path(year: @events[0].date.year-1, month: @events[0].date.month)
  = link_to '<', user_calendar_path(year: @events[0].date.month == 1 ? @events[0].date.year-1 : @events[0].date.year, month: @events[0].date.month == 1 ? 12 : @events[0].date.month-1)
  = link_to '>', user_calendar_path(year: @events[0].date.month == 12 ? @events[0].date.year+1 : @events[0].date.year, month: @events[0].date.month == 12 ? 1 : @events[0].date.month.next)
  = link_to '>>', user_calendar_path(year: @events[0].date.year.next, month: @events[0].date.month)
.clearfix
%table.table.table-bordered.table-calendar
  %thead
    %tr
      %th Понедельник
      %th Вторник
      %th Среда
      %th Четверг
      %th Пятница
      %th Суббота
      %th Воскресенье
  - @offset.times do
    %td
  - @events.each_with_index do |day, day_num|
    %td{id: day_num+1}
      %span.pull-left.day= day.date.day
      %span.pull-right.count
        = day.events.count_to_show
        - if day.events.count > 1
          %br
          %a.show_all{id: day_num+1} Показать все
          %a.hide.hide_all{id: day_num+1} Скрыть все
      %span.clearfix
        %table.table.table-event
          - if day.events.count == 0
            %tr
              %td
                %i.center Нет событий
          - else
            - day.events.each_with_index do |event, ind|
              %tr
                - if ind == 0
                  %td
                    %span.title-event.clickable{id: "#{day_num+1}-#{event.id}"}= event.title
                    %span.hide.form-event{id: "#{day_num+1}-#{event.id}"}
                      = simple_form_for event, url: user_event_path(event), html: {class: 'form-horizontal'} do |f|
                        = f.text_field :title, class: 'form-control title-event pull-left', placeholder: 'Название'
                    = link_to '', user_event_path(event), data: { confirm: 'Вы уверены?' }, method: :delete, class: 'glyphicon glyphicon-remove pull-right'
                    %span.clearfix
                - else
                  %td.toggleable.hide
                    %span.title-event.clickable{id: "#{day_num+1}-#{event.id}"}= event.title
                    %span.hide.form-event{id: "#{day_num+1}-#{event.id}"}
                      = simple_form_for event, url: user_event_path(event), html: {class: 'form-horizontal'} do |f|
                        = f.text_field :title, class: 'form-control title-event pull-left', placeholder: 'Название'
                    = link_to '', user_event_path(event), data: { confirm: 'Вы уверены?' }, method: :delete, class: 'glyphicon glyphicon-remove pull-right'
                    %span.clearfix
    - if day.date.wday == 0
      %tr

app/views/web/user/events/edit.html.haml
= simple_form_for @event, url: user_events_path, html: {class: 'form-horizontal'} do |f|
  - if @event.errors.any?
    .alert.alert-danger
      %a.close{"data-dismiss" => "alert"} ×
      = @event.errors.full_messages[0]
  .sec.sec-dark
    %div
      %h4 Изменить событие
    .form-group
      = f.label :title, class: 'col-sm-2 control-label'
      .col-sm-8
        = f.text_field :title, class: 'form-control', placeholder: 'Название'
    .form-group
      .col-sm-offset-2.col-sm-8
        = f.submit 'Создать', class: 'btn btn-default btn-block'

app/views/web/user/events/new.html.haml
= simple_form_for @event, url: user_events_path, html: {class: 'form-horizontal'} do |f|
  - if @event.errors.any?
    .alert.alert-danger
      %a.close{"data-dismiss" => "alert"} ×
      = @event.errors.full_messages[0]
  .sec.sec-dark
    %div
      %h4 Создать событие
    .form-group
      = f.label :title, class: 'col-sm-2 control-label'
      .col-sm-8
        = f.text_field :title, class: 'form-control', placeholder: 'Название'
    .form-group
      = f.label :date, class: 'col-sm-2 control-label'
      .col-sm-8
        = f.date_select :date, class: 'form-control', placeholder: 'Дата'
    .form-group
      = f.label :reiteration, class: 'col-sm-2 control-label'
      .col-sm-8
        = f.select :reiteration, Event.reiterations.keys, include_blank: false
    .form-group
      .col-sm-8.col-sm-offset-2
        = f.input :private
    .form-group
      .col-sm-offset-2.col-sm-8
        = f.submit 'Создать', class: 'btn btn-default btn-block'

app/views/web/user/settings/edit.html.haml
- if @user.errors.any?
  .alert.alert-danger
    %a.close{"data-dismiss" => "alert"} ×
    = @user.errors.full_messages[0]
= simple_form_for @user, url: user_setting_path, method: :patch, html: {class: 'form-horizontal'} do |f|
  .sec.sec-dark
    %h4 Персональная информация
    .form-group
      = f.label :name, class: 'col-sm-2 control-label'
      .col-sm-8
        = f.text_field :name, class: 'form-control', placeholder: 'Имя'
    .form-group
      = f.label :surname, class: 'col-sm-2 control-label'
      .col-sm-8
        = f.text_field :surname, class: 'form-control', placeholder: 'Фамилия'
    .form-group
      = f.label :email, class: 'col-sm-2 control-label'
      .col-sm-8
        = f.text_field :email, class: 'form-control', placeholder: 'Email'
    .form-group
      .col-sm-offset-2.col-sm-8
        = link_to 'Изменить пароль', edit_password_user_setting_path
    .form-group
      .col-sm-offset-2.col-sm-8
        = f.submit 'Сохранить', class: 'btn btn-default btn-block'

/ = simple_form_for UserEditForm.new, url: web_user_path, method: :patch, html: {class: 'form-horizontal'} do |f|
/   .sec.sec-dark
/     %h4 Защита
/     .form-group
/       = f.label :email, class: 'col-sm-2 control-label'
/       .col-sm-8
/         = f.text_field :email, class: 'form-control', placeholder: 'Email'
/     .form-group
/       = f.label :password, class: 'col-sm-2 control-label'
/       .col-sm-8
/         = f.input_field :password, class: 'form-control', type: :password, placeholder: 'Введите старый пароль'
/     .form-group
/       = f.label :password, class: 'col-sm-2 control-label'
/       .col-sm-8
/         = f.input_field :password, class: 'form-control', type: :password, placeholder: 'Новый пароль'
/     .form-group
/       .col-sm-offset-2.col-sm-8
/         = f.submit "Сохранить", class: 'btn btn-default btn-block'

app/views/web/user/settings/edit_password.html.haml
- if @user.errors.any?
  .alert.alert-danger
    %a.close{"data-dismiss" => "alert"} ×
    = @user.errors.full_messages[0]
= simple_form_for UserUpdatePasswordForm.new, url: update_password_user_setting_path, method: :patch, html: {class: 'form-horizontal'} do |f|
  .sec.sec-dark
    %h4 Изменить пароль
    .form-group
      = f.label :old_password, class: 'col-sm-2 control-label'
      .col-sm-8
        = f.text_field :old_password, class: 'form-control', type: :password, placeholder: 'Старый пароль'
    .form-group
      = f.label :new_password, class: 'col-sm-2 control-label'
      .col-sm-8
        = f.text_field :new_password, class: 'form-control', type: :password, placeholder: 'Новый пароль'
    .form-group
      .col-sm-offset-2.col-sm-8
        = link_to 'Изменить персональную информацию', edit_user_setting_path
    .form-group
      .col-sm-offset-2.col-sm-8
        = f.submit 'Сохранить', class: 'btn btn-default btn-block'

/ = simple_form_for UserEditForm.new, url: web_user_path, method: :patch, html: {class: 'form-horizontal'} do |f|
/   .sec.sec-dark
/     %h4 Защита
/     .form-group
/       = f.label :email, class: 'col-sm-2 control-label'
/       .col-sm-8
/         = f.text_field :email, class: 'form-control', placeholder: 'Email'
/     .form-group
/       = f.label :password, class: 'col-sm-2 control-label'
/       .col-sm-8
/         = f.input_field :password, class: 'form-control', type: :password, placeholder: 'Введите старый пароль'
/     .form-group
/       = f.label :password, class: 'col-sm-2 control-label'
/       .col-sm-8
/         = f.input_field :password, class: 'form-control', type: :password, placeholder: 'Новый пароль'
/     .form-group
/       .col-sm-offset-2.col-sm-8
/         = f.submit "Сохранить", class: 'btn btn-default btn-block'